name: AWS upload.
on: push
  

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
       
      - name: Installing all dependencies 
        run: |
            python -m pip install --upgrade pip
            pip install awscli
            pip3.10 install boto3
   
      - name: execute py script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            pip3.10 install boto3
            python connect_aws.py


          
      
