name: Copy Contents from Another Repository

on: push
  


jobs:
  copy_contents:
    runs-on: ['self-hosted', 'Windows', 'X64']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: maindir/Github-Action-Demo

    - name: Dir the workspace
      shell: cmd
      run: |      
          dir

    - name: Dir the maindir
      shell: cmd
      run: |      
          dir maindir
          
    - name: Checkout Automation branch
      uses: actions/checkout@v4
      with:
          repository: chaudharyvikash/Automation
          path: maindir/Automation         
          token: ${{ secrets.NEW_PAT }}

    - name: Dir the workspace - automation
      shell: cmd
      run: |      
          dir

    - name: Dir the maindir - automation
      shell: cmd
      run: |      
          dir maindir
    - name: Set up Git and copy
      shell: cmd
      run: |      
          cd maindir/Automation
          dir
          IF exist "test" ( echo folder exists ) ELSE ( echo folder not exists )
                
          copy data.zip ./../Github-Action-Demo/data/cache1 /E /Y
     
          
          
          
   
