name: Copy Contents from Another Repository

on: push
  


jobs:
  copy_contents:
    runs-on: ['self-hosted', 'Windows', 'X64']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          path: ${{ github.repository }}

    - name: Checkout Automation branch
      uses: actions/checkout@v3    
      with:
          repository: chaudharyvikash/Automation          
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ${{ github.repository_owner }}/Automation
        

    - name: Set up Git and copy
      shell: cmd
      run: |
          cd ${{ github.repository }}          
          IF exist "Automation/data.zip" ( echo data.zip exists ) ELSE ( echo data.zip not exists )
     
          
          
          
   
