name: Copy Contents from Another Repository

on: push
  


jobs:
  copy_contents:
    runs-on: ['self-hosted', 'Windows', 'X64']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Dir the workspace
      shell: cmd
      run: |      
          dir
          
    - name: Checkout Automation branch
      uses: actions/checkout@v4
      with:
          repository: chaudharyvikash/Automation
          path: Github-Action-Demo/Automation         
          token: ${{ secrets.NEW_PAT }}

    - name: Dir the workspace
      shell: cmd
      run: |      
          dir
    # - name: Set up Git and copy
    #   shell: cmd
    #   run: |      
    #       cd chaudharyvikash/Automation
    #       dir
    #       IF exist "test" ( echo folder exists ) ELSE ( echo folder not exists )
                
    #       copy data.zip ./../Github-Action-Demo/data/cache1 /E /Y
     
          
          
          
   
