name: Copy Contents from Another Repository

on: push
  


jobs:
  copy_contents:
    runs-on: ['self-hosted', 'Windows', 'X64']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          path: chaudharyvikash/Github-Action-Demo

          
    - name: Checkout Automation branch
      uses: actions/checkout@v4
      with:
          repository: chaudharyvikash/Automation
          path: chaudharyvikash/Automation         
          token: ${{ secrets.NEW_PAT }}
    - name: Set up Git and copy
      shell: cmd
      run: |      
          cd chaudharyvikash/Automation
          dir
          IF exist "test" ( echo folder exists ) ELSE ( echo folder not exists )
                
          copy data.zip ./../Github-Action-Demo/data/cache1 /E /Y
     
          
          
          
   
