name: Copy Contents from Another Repository

on: push
  


jobs:
  copy_contents:
    runs-on: ['self-hosted', 'Windows', 'X64']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          path: ${{ github.repository }}

          
    - name: Checkout Automation branch
      uses: actions/checkout@v4
      with:
          repository: chaudharyvikash/Automation
          path: ${{ github.repository }}/Automation          
          token: ${{ secrets.NEW_PAT }}
    - name: Set up Git and copy
      shell: cmd
      run: |      
          cd ${{ github.repository_owner }}/Automation
          dir
          IF exist "test" ( echo folder exists ) ELSE ( echo folder not exists )
          dir "test" /s
         
          xcopy /Y data.zip ./../Github-Action-Demo/data/cache1 /E
     
          
          
          
   
