name: Create Branch and Commit

on: push
  #workflow_dispatch:

jobs:
  create-branch-and-commit:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Generate branch name
        id: branch_name_generator
        run: |
          echo "::set-output name=generated_branch_name::$(date +'%Y_%m_%d')"
      
      - name: Create new branch of site repo
        id: create_branch
        run: |
          cd chaudharyvikash/Automation
          echo "::set-output name=local_site_folder::$(pwd)"
          git checkout -b ${{ steps.branch_name_generator.outputs.generated_branch_name }}

      - name: Commit changes
        run: |
          git add .
          git config --local user.email "chaudharyvikash2012@gmail.com"
          git config --local user.name "chaudharyvikash"
          git commit -m "Add new file"
      
      # - name: Push changes
      #   uses: ad-m/github-push-action@v0.7.0
      #   with:
      #     branch: dev-branch
      #     github_token: ${{ secrets.NEW_PAT }}
