name: Create Branch and Commit

on: push
  #workflow_dispatch:

jobs:
  create-branch-and-commit:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
           clean: true
           path: Github-Action-Demo 

      - name: Checkout Automation branch
        uses: actions/checkout@v3
        with:
          clean: true
          repository: chaudharyvikash/Automation
          path: Automation         
          token: ${{ secrets.NEW_PAT }}

      # - name: Generate branch name with shell script
      #   id: generate-branch-name
      #   run: echo "::set-output name=branch_name::$(Get-Date -Format 'yyyy-MM-dd')"

      - name: Create new branch
        run: |
          dir
          cd Automation
          git branch
          git checkout -b 2024-03-08
          #${{ steps.generate-branch-name.outputs.branch_name }}
          git rm -rf .
          dir

      - name: Write file
        run: |
         cd Automation
         echo "Hello, world!" > new-file.txt
      
      - name: Commit changes
        run: |
          dir
          cd Automation
          git add .
          git config user.email "chaudharyvikash2012@gmail.com"
          git config user.name "chaudharyvikash"
          git commit -m "Add new file"
          git push origin -u 2024-03-08
          #${{ steps.generate-branch-name.outputs.branch_name }}
        
    
