name: Create Branch and Commit

on: push
  #workflow_dispatch:

jobs:
  create-branch-and-commit:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create new branch
        run: |
          git checkout -b dev-branch
          git branch # optional - for verification

      - name: Write file
        run: |
          echo "Hello, world!" > new-file.txt
          type new-file.txt # optional - for verification

      - name: Commit changes
        run: |
          git add .
          git config --local user.email "chaudharyvikash2012@gmail.com"
          git config --local user.name "chaudharyvikash"
          git commit -m "Add new file"
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          branch: dev-branch
          github_token: ${{ secrets.NEW_PAT }}
