name: Generate file name with current date

on: push
      
jobs:
  generate-name:
    runs-on: [windows-latest]
    steps:
    # - name: Generate branch name
    #   id: branch_name_generator
    #   run: |
    #       echo "::set-output name=generated_branch_name::$(date +'%Y_%m_%d_%T' | tr : - | tr / -)"
    #       echo "Branch name: $outputs.generated_branch_name"

    - name: generate name with date
      run: |
          # Get the current date in the format "yyyymmdd"
          $branchDate = (Get-Date -Format "yyyyMMdd")
          
          # Generate the branch name
          $branchName = "${branchDate}_Status_Report.csv"
          
          # Output the branch name
          echo "Branch Name: $branchName"

          # Optionally, set this as an output for other steps
          echo "::set-output name=generated_branch_name::$branchName"
          echo "New name: $outputs.generated_branch_name"
