name: Check File Modified.

on:
  pull_request_target:
    types:
      - closed
    paths:
      - '**_Status_Report.csv'  # Specify the file to monitor for changes

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest  # Or windows-latest, depending on your environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout  branch
        uses: actions/checkout@v3
        with:
          repository: chaudharyvikash/Automation
          path: ${{ github.repository_owner }}/Automation         
          token: ${{ secrets.NEW_PAT }}
      - name: Run main.py
        run: |
            cd ${{ github.repository_owner }}/Automation
            python sysinfo.py
