name: Testing schedule run on working days.

on:
  schedule:
    - cron: "*/2 * * * 1-5"    #runs 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
     
      - name: execute py script # run file
        run: |
          python main.py
